// <auto-generated />
using System;
using Actividad5LengProg3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Actividad5LengProg3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Actividad5LengProg3.Models.Entities.Carrera", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("CantidadCreditos")
                        .HasColumnType("int");

                    b.Property<int>("CantidadMaterias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Codigo");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            CantidadCreditos = 150,
                            CantidadMaterias = 40,
                            Nombre = "Administración de Empresas"
                        },
                        new
                        {
                            Codigo = 2,
                            CantidadCreditos = 145,
                            CantidadMaterias = 38,
                            Nombre = "Contabilidad"
                        },
                        new
                        {
                            Codigo = 3,
                            CantidadCreditos = 160,
                            CantidadMaterias = 42,
                            Nombre = "Derecho"
                        },
                        new
                        {
                            Codigo = 4,
                            CantidadCreditos = 155,
                            CantidadMaterias = 41,
                            Nombre = "Psicología Clínica"
                        },
                        new
                        {
                            Codigo = 5,
                            CantidadCreditos = 148,
                            CantidadMaterias = 39,
                            Nombre = "Orientación Escolar"
                        },
                        new
                        {
                            Codigo = 6,
                            CantidadCreditos = 150,
                            CantidadMaterias = 40,
                            Nombre = "Administración y Supervisión Escolar"
                        },
                        new
                        {
                            Codigo = 7,
                            CantidadCreditos = 165,
                            CantidadMaterias = 44,
                            Nombre = "Enfermería"
                        },
                        new
                        {
                            Codigo = 8,
                            CantidadCreditos = 180,
                            CantidadMaterias = 48,
                            Nombre = "Odontología"
                        },
                        new
                        {
                            Codigo = 9,
                            CantidadCreditos = 170,
                            CantidadMaterias = 46,
                            Nombre = "Ingeniería"
                        },
                        new
                        {
                            Codigo = 10,
                            CantidadCreditos = 152,
                            CantidadMaterias = 40,
                            Nombre = "Ciencias Naturales"
                        });
                });

            modelBuilder.Entity("Actividad5LengProg3.Models.Entities.Estudiante", b =>
                {
                    b.Property<string>("Matricula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Becado")
                        .HasColumnType("bit");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PorcentajeBeca")
                        .HasColumnType("int");

                    b.Property<int>("RecintoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TurnoEstudiante")
                        .HasColumnType("int");

                    b.HasKey("Matricula");

                    b.HasIndex("CarreraId");

                    b.HasIndex("CorreoInstitucional")
                        .IsUnique();

                    b.HasIndex("RecintoId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Actividad5LengProg3.Models.Entities.Recinto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Codigo");

                    b.ToTable("Recintos");

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Direccion = "Santo Domingo Oeste",
                            Nombre = "Herrera"
                        },
                        new
                        {
                            Codigo = 2,
                            Direccion = "Santo Domingo Este",
                            Nombre = "Metropolitano"
                        },
                        new
                        {
                            Codigo = 3,
                            Direccion = "Barahona",
                            Nombre = "Barahona"
                        });
                });

            modelBuilder.Entity("Actividad5LengProg3.Models.Entities.Estudiante", b =>
                {
                    b.HasOne("Actividad5LengProg3.Models.Entities.Carrera", "Carrera")
                        .WithMany("Estudiantes")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Actividad5LengProg3.Models.Entities.Recinto", "Recinto")
                        .WithMany("Estudiantes")
                        .HasForeignKey("RecintoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Recinto");
                });

            modelBuilder.Entity("Actividad5LengProg3.Models.Entities.Carrera", b =>
                {
                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("Actividad5LengProg3.Models.Entities.Recinto", b =>
                {
                    b.Navigation("Estudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
